### ISSUE TITLE
模块重构、服务重构和单体重构的区别和联系在哪里

### ISSUE THREAD

**Issue by victoryw** [phodal/migration#1]
问题：
这三种重构放在一个水平，我有些疑惑
模块可以是服务的一部分
模块是单体的一部分
层是一个模块么
一个服务也可以是一个大的模块
这里的模块定义感觉有些模糊？

**Comment by phodal** [comment]
这里的模块重构 = 组件重构，module 级别的，我应该在下一个版本里改成 module 重构

**Comment by ileadall42** [comment]
我想问一下这方面的知识主要是靠经验积累还是说也有这方面很经典可以指导的书籍呢 0 0？谢谢解答啦！

**Comment by phodal** [comment]
@ileadall42 文中提到的很多书都包含了相关的内容：

 - 《重构与模式》
 - 《设计模式：可复用面向对象软件的基础》
 - 《重构：改善既有代码的设计》
 - 《领域驱动设计：软件核心复杂性应对之道》
 - 《修改代码的艺术：构建易维护代码的 9 条最佳实践》
 - 《代码整洁之道》
 - 《架构整洁之道》
 - 《数据库重构》
 - 《遗留系统重构指南》
 
不过呢，你的结合着去尝试做几次项目重构，就会拥有这方面的经验。所以，你可以尝试结合这个项目的内容来构建你的重构知识体系。

**Comment by ileadall42** [comment]
谢谢你啦，太棒了这个书单！@phodal
