### ISSUE TITLE
《遗留系统重构指南》这本书请教一个问题

### ISSUE THREAD

**Issue by xiaozhiliaoo** [phodal/migration#5]
这本书说jenkins+pmd+checkstyle进行持续审查，可以做到只对增量代码审查吗，历史问题太多，需要逐步推进，感谢！

**Comment by phodal** [comment]
Sonar 是可以的。

**Comment by xiaozhiliaoo** [comment]
如果不用sonar是不是做不到了呀？

**Comment by phodal** [comment]
别的没试过…

**Comment by xiaozhiliaoo** [comment]
sonar community 不支持增量，您用的是哪一个版本呢？

**Comment by phodal** [comment]
没啥印象了……，之前在别的项目用过，这个是 DevOps 做的事情，不是开发管的。

**Comment by xiaozhiliaoo** [comment]
好的，非常感谢  ^_^
